Add SWA in optimizers.__init__
to fix the following error when `tfa.optimizers.SWA` is used:
AttributeError: module 'tensorflow_addons.optimizers' has no attribute 'SWA'